### ISSUE TITLE
Fartseer

### ISSUE THREAD

**Issue by sshaileshk** [Spanfile/Fartseer#1]
Cannot compile the code using Microsoft XNA 4.0. Used SMFL libraries 2.0. Also error in World rendered.cs file - 
The best overloaded method match for 'Fartseer.Line.Line(SFML.Window.Vector2f, SFML.Window.Vector2f, SFML.Graphics.Color, double)' has some invalid arguments

Can this be fixed.

**Comment by Spanfile** [comment]
The whole project uses SFML.NET as a base. Switching to XNA would require a lot of work, since you'd have to completely change how rendering is done, change all SFML-specific types to their XNA counterparts, and generally completely change how the game works.
